### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by FrankFang** [axemclion/browser-perf#12]
```
~/Downloads ❯❯❯ sudo npm install -g browser-perf
/Users/frank/.nvm/v0.10.21/bin/browser-perf -> /Users/frank/.nvm/v0.10.21/lib/node_modules/browser-perf/lib/cli.js
browser-perf@0.1.12 /Users/frank/.nvm/v0.10.21/lib/node_modules/browser-perf
├── commander@2.2.0
├── jsmin@1.0.1
├── q@1.0.1
├── cli-table@0.3.0 (colors@0.6.2)
├── byline@4.1.1
└── wd@0.2.27 (vargs@0.1.0, async@0.9.0, underscore.string@2.3.3, request@2.36.0, lodash@2.4.1, archiver@0.10.0)
~/Downloads ❯❯❯ browser-perf http://hi.com --browsers=chrome
env: node\r: No such file or directory
```

Mac OS 10.9.3

**Comment by dreamzmaster** [comment]
I am again having this issue.

```
$ browser-perf
env: node\r: No such file or directory
```

**Comment by axemclion** [comment]
@dreamzmaster Which version of browser-perf are you using, and what is your platform ?

**Comment by dreamzmaster** [comment]
I am using Mac OSX

Version:
```
$ npm install -g browser-perf
/usr/local/bin/browser-perf -> /usr/local/lib/node_modules/browser-perf/lib/cli.js
browser-perf@1.2.6 /usr/local/lib/node_modules/browser-perf
├── jsmin@1.0.1
├── q@1.4.1
├── byline@4.2.1
├── debug@2.2.0 (ms@0.7.1)
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── cli-table@0.3.1 (colors@1.0.3)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
└── wd@0.3.11 (vargs@0.1.0, q@1.0.1, async@0.9.2, underscore.string@2.3.3, lodash@2.4.2, request@2.46.0, archiver@0.12.0)
$ browser-perf
env: node\r: No such file or directory
```

**Comment by axemclion** [comment]
@dreamzmaster Fixed now - looks like this was due to line endings.

**Comment by matiassingers** [comment]
@axemclion running this might fix this for you:

```sh
$ git config --global core.autocrlf input
```

But the issue could still show up on other machines without this setting, so creating a `.gitattributes` in the repo with this:
```
# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto
```

**Comment by axemclion** [comment]
This was set on a mac machine - i tried editing code using a new machine, hence the screw up.

**Comment by developit** [comment]
This is happening again.

**Comment by dkozma** [comment]
Can confirm this is happening again (OS X 10.11.2, Node v5.4.0, NPM 3.3.12).

**Comment by developit** [comment]
Editing the file to use LF fixes it.

**Comment by axemclion** [comment]
Can you send in a pull request for this please ? I should be able to merge it.

**Comment by axemclion** [comment]
@dkozma @developit, I just published a new version. That should have this fixed. Also pushed a .gitattributes file. Can you check if that works  ?

**Comment by developit** [comment]
@axemclion confirmed, that fixed it. Thanks! Just writing a JSON reporter now :)

**Comment by dkozma** [comment]
Verified on my env as well - thanks @axemclion!

**Comment by axemclion** [comment]
@developit @dkozma Thanks for verifying. I added a .gitattributes, so this should not be a problem anymore
